/*
 * Shape options for the intersection of three-way traps.
 *
 *
 * OMV Name: 17.0
 * OMV Time: 3-21-2022 16:34:19
 * OMV Title: Adobe InDesign 2022 (17.0) Object Model
 */
var TrapEndTypes = {


    /**
     * Shapes the end of the trap to keep it away from the intersecting object.
     * @type {number}
     * @readonly
     */
    MITER_TRAP_ENDS: 1953525093,


    /**
     * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
     * @type {number}
     * @readonly
     */
    OVERLAP_TRAP_ENDS: 1953525612,




};

