/*
 * Shape options for the intersection of three-way traps.
 *
 *
 * OMV Name: 16.1
 * OMV Time: 3-31-2021 11:1:40
 * OMV Title: Adobe InDesign 2021 (16.1) Object Model
 */
var TrapEndTypes = {


    /**
     * Shapes the end of the trap to keep it away from the intersecting object.
     * @type {number}
     * @readonly
     */
    MITER_TRAP_ENDS: 1953525093,


    /**
     * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
     * @type {number}
     * @readonly
     */
    OVERLAP_TRAP_ENDS: 1953525612,




};

